### ISSUE TITLE
`keys` should include the prefix

### ISSUE THREAD

**Issue by fixe** [linus/refix#2]
Currently  the `keys` command is returning all keys from the Redis database but It should only return the prefixed keys.

Also, since commands such as `del` already append the prefix, it should return un-prefixed keys.

In Redis we have:

```
foo:bar 1
qux:biz 2
```

If we setup `refix` to use the prefix `foo`, the `keys` command should return `bar`.

**Comment by linus** [comment]
@fixe sorry, done.
